substitutions:
  name: wpboiler
  friendlyname: Atlantic
  comment: Atlantic Explorer warmtepomp Boiler

esphome:
  name: ${name}
  friendly_name: ${friendlyname}
  comment: ${comment}
  on_boot:
    priority: 200
    then:
      - delay: 30s
#      - switch.turn_off:
#          id: m5stack_led_switch

esp32:
  board: m5stack-atom
#  framework:
#    type: esp-idf
#  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

# Enable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN 

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable Over The Air updates  
ota:
  platform: esphome
#  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    
captive_portal:
    
web_server:
  port: 80

## Option for 2x I2C connectors
## Comment with # if not used.
i2c:  
  - id: bus_a
    sda: 25
    scl: 21
    scan: true

  - id: bus_b
    sda: 26
    scl: 32
    scan: true


###  ESP restart button
button:
  - platform: restart
    id: restart_button
    name: Esp restart

switch:
  ## Relay1
  - platform: gpio
    pin:
      number: GPIO22
      inverted: false
    name: Boost
    id: wp_relay1
#    internal: true
    icon: mdi:alarm-bell
  
  ## Relay2
#  - platform: gpio
#    pin:
#      number: GPIO19
#      inverted: false
#    name: Whatever
#    id: wp_relay2
#    internal: true
#    icon: mdi:alarm-bell

sensor:
  # M5stack KMeterIso - https://docs.m5stack.com/en/unit/KMeterISO%20Unit
  - platform: kmeteriso
    temperature:
      name: Boiler temperatuur
    internal_temperature:
      name: Internal temperature
      entity_category: diagnostic
    update_interval: 5s
    i2c_id: bus_a

#  # M5stack KMeterIso - https://docs.m5stack.com/en/unit/KMeterISO%20Unit
#  - platform: kmeteriso
#    temperature:
#      name: Condensor temperatuur
#    internal_temperature:
#      name: Internal temperature 2
#      entity_category: diagnostic
#    update_interval: 5s
#    i2c_id: bus_b
