substitutions:
  name: atoms3_enviii
  device_description: "Esphome component for M5stack ENVIII sensor"
  timezone: "Europe/Amsterdam"

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: "configesp"
 
captive_portal:

# Sync time with sntp server
time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}

# Enable logging
logger:
  baud_rate: 0
  level: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s
 
ota:
  platform: esphome

web_server:
  port: 80

i2c:
  - id: bus_a
    sda: GPIO2
    scl: GPIO1

sensor:
  # M5stack environmental sensor ENVIII - https://docs.m5stack.com/en/unit/envIII
  - platform: sht3xd
    temperature:
      name: Room Temperature #envIII_temperature
      id: room_temp #enviii_temperature 
    humidity:
      name: Room RH #envIII_humidity 
      id: room_rh #enviii_humidity
    i2c_id: bus_a
    address: 0x44
    update_interval: 30s

  - platform: qmp6988
#    temperature:
#      name: "Room Temperature2 ENVIII"
#      oversampling: 16x
    pressure:
      name: barometric pressure
      id: barometric_pressure
      oversampling: 16x
    i2c_id: bus_a
    address: 0x70
    update_interval: 30s
    iir_filter: 2x
