substitutions:
  name: atoms3_kmeter_iso
  device_description: "Esphome component for KMeterIso Unit"
  timezone: "Europe/Amsterdam"

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: "configesp"
 
captive_portal:

# Sync time with sntp server
time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}

# Enable logging
logger:
  baud_rate: 0
  level: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s
 
ota:

web_server:
  port: 80

i2c:
  - id: bus_a
    sda: GPIO2
    scl: GPIO1
#    frequency: 100kHz

sensor:
  # M5stack KMeterIso - https://docs.m5stack.com/en/unit/KMeterISO%20Unit
  - platform: kmeteriso
    temperature:
      name: Temperature
    internal_temperature:
      name: Internal temperature
      entity_category: diagnostic
    update_interval: 5s